const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'/Users/baobei/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
const root=path.resolve(__dirname,'..'),browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});const errors=[],external=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url())});
await page.goto('file://'+path.join(root,'index.html'));assert((await page.evaluate(()=>window.__selftest())).ok);
assert(await page.locator('#hsqc .peak.ch2').count()===0);
assert(await page.locator('#edited .peak.ch2').count()===4);
const result={selftest:await page.evaluate(()=>window.__selftest()),interactions:[],layouts:[],errors,external};
for(const id of [1,2,4,5,6,7]){await page.locator(`#pickList button[data-id="${id}"]`).click();assert((await page.locator('#readouts').textContent()).includes(`C${id}`));assert(await page.locator('#hsqc .peak.selected').getAttribute('data-id')===String(id));assert(await page.locator('#edited .peak.selected').getAttribute('data-id')===String(id));assert(await page.locator('#structure .atom.selected').count()===1);result.interactions.push('select C'+id)}
await page.locator('#structure .atom-group[data-id="4"]').focus();await page.keyboard.press('Enter');assert((await page.locator('#readouts').textContent()).includes('C4'));result.interactions.push('keyboard structure');
await page.locator('#edited .peak[data-id="7"]').focus();await page.keyboard.press('Space');assert((await page.locator('#readouts').textContent()).includes('C7'));result.interactions.push('keyboard spectrum');
await page.locator('#assignmentRows tr[data-id="2"]').click();assert((await page.locator('#readouts').textContent()).includes('C2'));result.interactions.push('assignment table');
let before=await page.locator('#zoomPlot').innerHTML();await page.locator('#zoom').fill('0.12');assert(before!==await page.locator('#zoomPlot').innerHTML());assert((await page.locator('#zoomValue').textContent()).includes('0.12'));result.interactions.push('zoom slider');
await page.locator('#threshold').fill('0');assert(!(await page.locator('#overlapText').textContent()).includes('C4'));await page.locator('#threshold').fill('0.35');assert((await page.locator('#overlapText').textContent()).includes('C4'));assert(await page.locator('#hsqc .halo').count()>0);result.interactions.push('threshold boundaries');
await page.locator('#threshold').fill('0.08');await page.locator('#zoom').fill('0.35');
for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});await page.waitForFunction(w=>document.querySelector('#structure').getAttribute('viewBox')===(w<751?'0 0 285 380':'0 0 690 165'),width);const layout=await page.evaluate(()=>({viewport:innerWidth,scroll:document.documentElement.scrollWidth,structure:document.querySelector('#structure').getBoundingClientRect().width,structureViewBox:document.querySelector('#structure').getAttribute('viewBox'),zoomViewBox:document.querySelector('#zoomPlot').getAttribute('viewBox'),charts:[...document.querySelectorAll('.plot')].map(x=>x.getBoundingClientRect().width),images:[...document.images].every(i=>i.complete&&i.naturalWidth>0)}));assert(layout.scroll<=width,JSON.stringify(layout));assert(layout.images);assert(layout.charts.every(x=>x>0));assert(layout.structureViewBox===(width<751?'0 0 285 380':'0 0 690 165'));assert(layout.zoomViewBox===(width<751?'0 0 410 265':'0 0 780 265'));result.layouts.push(layout);await page.screenshot({path:path.join(root,width===1440?'preview.png':`preview-${width}.png`),fullPage:true});}
await page.locator('details summary').click();assert(await page.locator('#originalImage').isVisible());result.interactions.push('original image');
const popupPromise=page.waitForEvent('popup');await page.locator('#openOriginal').click();const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded');assert(await popup.locator('img').count()===1);await popup.close();result.interactions.push('original new window');
await page.goto('file://'+path.resolve(root,'../../index.html'));assert((await page.locator('a[href="./topics/hsqc-edited-heptanone/index.html"]').count())===1);assert((await page.locator('.count').textContent()).includes('9 个'));result.interactions.push('repository directory link');
assert(errors.length===0,errors.join('; '));assert(external.length===0,external.join('; '));result.ok=true;result.browser=await browser.version();fs.writeFileSync(path.join(root,'verification.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
