(()=>{
const $=id=>document.getElementById(id),S={a:4,b:7,t:90,threshold:.15};
const get=id=>NMR.nodes.find(n=>n.id===id),colors={direct:'#5fd0a8',relay:'#f0bd6a',diagonal:'#b1bdcc',blocked:'#b1bdcc'};
const labels={direct:'● 直接耦合',relay:'◆ 接力关联',diagonal:'■ 对角位置',blocked:'— 无有效通路'};
const options=NMR.nodes.map(n=>`<option value="${n.id}">H${n.id} · ${n.kind} · ${n.system} 组</option>`).join('');$('origin').innerHTML=options;$('target').innerHTML=options;
function structure(){if(innerWidth<=760){structureMobile();return;}const coords={1:[52,100],2:[150,54],3:[250,100],4:[350,54],5:[450,100],6:[550,54],7:[648,100]};const p=NMR.path(S.a,S.b);let s='<svg viewBox="0 0 700 211" role="group" aria-label="可选择的 3-庚酮结构示意"><text x="4" y="18" fill="#b1bdcc" font-size="14">CH₃–CH₂–C(=O)–CH₂–CH₂–CH₂–CH₃</text>';
for(let n=1;n<7;n++){const [x,y]=coords[n],[xx,yy]=coords[n+1];s+=`<line x1="${x}" y1="${y}" x2="${xx}" y2="${yy}" stroke="#b1bdcc" stroke-width="3"/>`;}
s+='<line x1="245" y1="112" x2="245" y2="158" stroke="#b1bdcc" stroke-width="3"/><line x1="255" y1="112" x2="255" y2="158" stroke="#b1bdcc" stroke-width="3"/><text x="250" y="186" fill="#ff9e91" font-size="22" text-anchor="middle">O</text><text x="299" y="140" fill="#b1bdcc" font-size="12" text-anchor="middle">3 · 无氢</text>';
for(const [a,b]of NMR.edges){const [x,y]=coords[a],[xx,yy]=coords[b];const on=p&&p.includes(a)&&p.includes(b);s+=`<line x1="${x}" y1="${y}" x2="${xx}" y2="${yy}" stroke="${on?'#f0bd6a':'#5fd0a8'}" stroke-width="${on?6:3}"/>`;}
s+='<path d="M 150 75 Q 250 58 350 75" stroke="#657385" stroke-width="1.5" fill="none" stroke-dasharray="5 5"/><text x="250" y="53" fill="#b1bdcc" font-size="12" text-anchor="middle">2···4：此模型无边</text>';
for(const n of NMR.nodes){const [x,y]=coords[n.id],chosen=n.id===S.a||n.id===S.b,on=p&&p.includes(n.id),color=on?'#f0bd6a':n.system==='A'?'#82baff':'#5fd0a8';s+=`<g role="button" tabindex="0" data-pair="${n.id},${S.b}" aria-label="选择起点 H${n.id}，${n.kind}，${n.h} 个氢" aria-pressed="${n.id===S.a}"><rect x="${x-28}" y="${y-25}" width="56" height="62" fill="#151a21" stroke="${chosen?'#f0bd6a':color}" stroke-width="${chosen?3:1}" rx="5"/><text x="${x}" y="${y-6}" text-anchor="middle" fill="${color}" font-size="20" font-weight="600">${n.id}</text><text x="${x}" y="${y+21}" text-anchor="middle" fill="#eaf0f7" font-size="16">${n.kind}</text></g>`;}
s+='<text x="80" y="204" fill="#82baff" font-size="13">网络 A：1–2</text><text x="448" y="204" fill="#5fd0a8" font-size="13">网络 B：4–5–6–7</text></svg>';$('molecule').innerHTML=s;}
function structureMobile(){const coords={1:[75,60],2:[215,120],3:[75,180],4:[215,240],5:[75,300],6:[215,360],7:[75,420]},p=NMR.path(S.a,S.b);let s='<svg viewBox="0 0 300 500" role="group" aria-label="可选择的 3-庚酮结构示意，手机纵向排列"><text x="8" y="20" fill="#b1bdcc" font-size="14">3‑庚酮 · 结构与路径（示意）</text>';
for(let n=1;n<7;n++){const[x,y]=coords[n],[xx,yy]=coords[n+1];s+=`<line x1="${x}" y1="${y}" x2="${xx}" y2="${yy}" stroke="#b1bdcc" stroke-width="3"/>`;}
s+='<path d="M 85 173 H 139 M 85 183 H 139" stroke="#b1bdcc" stroke-width="3"/><text x="151" y="186" fill="#ff9e91" font-size="22">O</text><text x="47" y="187" text-anchor="middle" fill="#b1bdcc" font-size="17">3 · C</text><path d="M 241 125 Q 296 180 241 235" fill="none" stroke="#657385" stroke-dasharray="4 4"/><text x="269" y="180" fill="#b1bdcc" font-size="12" text-anchor="middle">无边</text>';
for(const[a,b]of NMR.edges){const[x,y]=coords[a],[xx,yy]=coords[b],on=p&&p.includes(a)&&p.includes(b);s+=`<line x1="${x}" y1="${y}" x2="${xx}" y2="${yy}" stroke="${on?'#f0bd6a':'#5fd0a8'}" stroke-width="${on?6:3}"/>`;}
for(const n of NMR.nodes){const[x,y]=coords[n.id],selected=n.id===S.a||n.id===S.b,color=p&&p.includes(n.id)?'#f0bd6a':n.system==='A'?'#82baff':'#5fd0a8';s+=`<g role="button" tabindex="0" data-pair="${n.id},${S.b}" aria-label="选择起点 H${n.id}，${n.kind}，${n.h} 个氢" aria-pressed="${n.id===S.a}"><rect x="${x-27}" y="${y-24}" width="54" height="52" rx="5" fill="#151a21" stroke="${selected?'#f0bd6a':color}" stroke-width="${selected?3:1}"/><text x="${x}" y="${y-4}" fill="${color}" text-anchor="middle" font-size="19">${n.id}</text><text x="${x}" y="${y+18}" fill="#eaf0f7" text-anchor="middle" font-size="15">${n.kind}</text></g>`;}
s+='<text x="8" y="467" fill="#82baff" font-size="14">网络 A：1–2</text><text x="8" y="490" fill="#5fd0a8" font-size="14">网络 B：4–5–6–7</text></svg>';$('molecule').innerHTML=s;}
function plot(mode){const xmin=.65,xmax=2.65,lo=52,hi=293,size=hi-lo,px=d=>lo+(xmax-d)/(xmax-xmin)*size,py=d=>lo+(d-xmin)/(xmax-xmin)*size;let s=`<svg viewBox="0 0 344 365" role="group" aria-label="${mode} 示意二维相关图，可点击峰选择组对"><rect x="${lo}" y="${lo}" width="${size}" height="${size}" fill="#10151c" stroke="#657385"/>`;
for(const tick of[1,1.5,2,2.5]){const x=px(tick),y=py(tick);s+=`<path d="M ${x} ${lo} V ${hi} M ${lo} ${y} H ${hi}" stroke="#283240" stroke-width="1"/><text x="${x}" y="${hi+22}" fill="#b1bdcc" font-size="12" text-anchor="middle">${tick.toFixed(1)}</text><text x="${lo-9}" y="${y+4}" fill="#b1bdcc" font-size="12" text-anchor="end">${tick.toFixed(1)}</text>`;}
s+=`<path d="M ${lo} ${hi} L ${hi} ${lo}" stroke="#657385" stroke-dasharray="3 6"/><text x="${hi}" y="359" fill="#b1bdcc" font-size="12" text-anchor="end">F₂ · ¹H / ppm</text><text x="12" y="205" transform="rotate(-90 12 205)" fill="#b1bdcc" font-size="12">F₁ · ¹H / ppm</text>`;
for(const n of NMR.nodes){const x=px(n.delta),y=py(n.delta);s+=`<text x="${x}" y="${n.id===4?38:23}" fill="${n.id===S.a?'#f0bd6a':'#b1bdcc'}" font-size="12" text-anchor="middle">${n.id}</text><text x="310" y="${y}" fill="${n.id===S.b?'#f0bd6a':'#b1bdcc'}" font-size="12">${n.id}</text>`;}
const sx=px(get(S.a).delta),sy=py(get(S.b).delta);s+=`<path d="M ${sx} ${lo} V ${hi} M ${lo} ${sy} H ${hi}" stroke="#f0bd6a" opacity=".55" stroke-dasharray="4 4"/>`;
for(const a of NMR.nodes)for(const b of NMR.nodes){const kind=NMR.relation(a.id,b.id),v=NMR.value(a.id,b.id,S.t,mode),visible=kind==='diagonal'||v>0&&v>=S.threshold;if(!visible)continue;const x=px(a.delta),y=py(b.delta),col=colors[kind],op=kind==='diagonal'?1:.28+.72*v;let mark=kind==='diagonal'?`<rect x="${x-3.5}" y="${y-3.5}" width="7" height="7" fill="${col}"/>`:kind==='direct'?`<circle cx="${x}" cy="${y}" r="4.7" fill="${col}"/>`:`<path d="M ${x} ${y-6} l 6 6 l -6 6 l -6 -6 Z" fill="${col}"/>`;s+=`<g role="button" tabindex="0" data-pair="${a.id},${b.id}" aria-label="${mode} H${a.id} 与 H${b.id}，${labels[kind]}，教学权重 ${v.toFixed(3)}" aria-pressed="${a.id===S.a&&b.id===S.b}"><circle cx="${x}" cy="${y}" r="10" fill="transparent"/><g opacity="${op}">${mark}</g></g>`;}
s+=`<circle cx="${sx}" cy="${sy}" r="11" fill="none" stroke="#f0bd6a" stroke-width="2" pointer-events="none"/><text x="${lo}" y="${hi+43}" fill="#b1bdcc" font-size="11">所有坐标与符号强度：教学示意</text></svg>`;$(mode==='COSY'?'cosyPlot':'tocsyPlot').innerHTML=s;const c=NMR.count(S.t,S.threshold,mode);$(mode==='COSY'?'cosyCount':'tocsyCount').textContent=`当前显示 ${c} 对 / ${c*2} 个非对角位置；另有 6 个对角标记。`;}
function matrix(){let html='<table class="relation-grid"><caption>有效网络的完整组对表 · 理论</caption><thead><tr><th scope="col">起→终</th>'+NMR.nodes.map(n=>`<th scope="col">${n.id}</th>`).join('')+'</tr></thead><tbody>';const symbol={direct:'●',relay:'◆',blocked:'—',diagonal:'■'};for(const a of NMR.nodes){html+=`<tr><th scope="row">${a.id}</th>`;for(const b of NMR.nodes){const k=NMR.relation(a.id,b.id);html+=`<td><button class="${k}" data-pair="${a.id},${b.id}" aria-label="H${a.id} 与 H${b.id}，${labels[k]}" aria-pressed="${a.id===S.a&&b.id===S.b}">${symbol[k]}</button></td>`;}html+='</tr>';}html+='</tbody></table>';$('relationMatrix').innerHTML=html;}
function assignment(){$('assignmentBody').innerHTML=NMR.nodes.map(n=>{const partners=NMR.edges.flatMap(([a,b])=>a===n.id?[b]:b===n.id?[a]:[]);return`<tr class="${n.id===S.a||n.id===S.b?'selected':''}"><td><button data-pair="${n.id},${S.b}">H${n.id}</button></td><td>${n.kind} · ${n.where}</td><td>${n.h} H</td><td>${n.estimate}</td><td>${n.delta.toFixed(2)}（人为）</td><td>${partners.join('、')}</td><td>${n.system}</td></tr>`;}).join('');}
function readout(){const k=NMR.relation(S.a,S.b),p=NMR.path(S.a,S.b),d=p?p.length-1:null,v=NMR.value(S.a,S.b,S.t,'TOCSY');$('kindTag').textContent=labels[k];$('pairTitle').textContent=`H${S.a} ↔ H${S.b}`;$('pathText').textContent=p?p.join(' → '):'1–2  ║  4–5–6–7';const show=v>0&&v>=S.threshold;const rows=[['x / 演示 ppm',get(S.a).delta.toFixed(2)],['y / 演示 ppm',get(S.b).delta.toFixed(2)],['最短路径',d===null?'无通路':`${d} 步`],['COSY 标记',NMR.value(S.a,S.b,S.t,'COSY')?'显示':'无'],['TOCSY 权重',`${v.toFixed(4)}（无单位）`],['TOCSY 标记',show?'显示':v===0?'权重为零':'低于阈值'],['起点 / 终点网络',`${get(S.a).system} / ${get(S.b).system}`]];$('readout').innerHTML=rows.map(([a,b])=>`<dt>${a}</dt><dd>${b}</dd>`).join('');
const prose={direct:'这对氢组在近邻模型中有一条直接有效 J 耦合边，所以 COSY 用圆点表示；TOCSY 也可沿同一条边转移。直接关联不能简单等同于“一键 H–H 成键”。',relay:`从 ${S.a} 到 ${S.b} 需要经过 ${d===null?'':d-1} 个中间氢组。因此它可在 TOCSY 产生接力关联，而在这里的近邻 COSY 模型中没有标记。观察到此关联不能据此确认两端直接相邻。`,blocked:'两侧分属 A 与 B；本页忽略跨羰基的弱四键耦合，所以没有有效通路。模型缺边不证明实际 J 严格为零。',diagonal:'这是同一氢组的对角位置，不是另一条连接。对角标记固定用于定位，不模拟它随混合时间变化的真实实验强度。'};
$('explanation').innerHTML=`<p><strong>为什么是这个结果？</strong></p><p>${prose[k]}</p><p><strong>当前显示：</strong>${show?'TOCSY 示意标记达到阈值。':v===0?'TOCSY 模型权重为零；金色空圈仅定位当前组对，不表示观察到峰。':'通路仍存在，但示意权重低于阈值；金色空圈只定位当前选择。'}</p><p class="small">读数来源：坐标与权重为演示；网络和步数为指定近邻模型推算。原图不提供这些精确数值。</p>`;}
function update(){const old=document.activeElement;const key=old?.dataset?.pair,container=old?.closest('#molecule,#cosyPlot,#tocsyPlot,#relationMatrix,#assignmentBody')?.id;$('origin').value=S.a;$('target').value=S.b;$('time').value=S.t;$('threshold').value=S.threshold;$('timeValue').textContent=`${S.t} ms`;$('thresholdValue').textContent=S.threshold.toFixed(2);structure();plot('COSY');plot('TOCSY');matrix();assignment();readout();document.querySelectorAll('.preset [data-pair]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.pair===`${S.a},${S.b}`));activateHTML();if(container&&key){const el=document.querySelector(`#${container} [data-pair="${key}"]`);if(el)el.focus({preventScroll:true});}}
// One-time delegation avoids duplicate listeners on persistent preset buttons.
function bindPairDelegation(){document.querySelector('.preset').addEventListener('click',e=>{const b=e.target.closest('[data-pair]');if(b){[S.a,S.b]=b.dataset.pair.split(',').map(Number);update();}});}
// Only generated elements get direct activation handlers.
function activateHTML(){document.querySelectorAll('#molecule [data-pair],#cosyPlot [data-pair],#tocsyPlot [data-pair],#relationMatrix [data-pair],#assignmentBody [data-pair]').forEach(el=>{el.addEventListener('click',()=>{[S.a,S.b]=el.dataset.pair.split(',').map(Number);update();});if(el.tagName.toLowerCase()==='g')el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.dispatchEvent(new Event('click'));}});});};
$('origin').addEventListener('change',e=>{S.a=+e.target.value;update();});$('target').addEventListener('change',e=>{S.b=+e.target.value;update();});$('time').addEventListener('input',e=>{S.t=+e.target.value;update();});$('threshold').addEventListener('input',e=>{S.threshold=+e.target.value;update();});$('reset').addEventListener('click',()=>{Object.assign(S,{a:4,b:7,t:90,threshold:.15});$('quizFeedback').textContent='选择答案查看解释。';update();});$('runSelftest').addEventListener('click',()=>{const r=NMR.selftest();$('testStatus').textContent=r.ok?`通过 ${Object.keys(r.checks).length} 项模型检查。真实谱图未定量验证。`:'检查失败，请查看源码与验证记录。';});document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{$('quizFeedback').textContent=b.dataset.answer==='correct'?'正确。支持同一有效网络；直接相邻和真实 J 是否为零仍需额外证据。':'再想想：TOCSY 可经中间氢组接力，不能仅凭该关联确定直接相邻或 J 的精确值。';}));
for(const el of document.querySelectorAll('[data-math]'))katex.render(el.dataset.math,el,{displayMode:true,throwOnError:true});bindPairDelegation();update();let narrow=innerWidth<=760;addEventListener('resize',()=>{if(narrow!==(innerWidth<=760)){narrow=innerWidth<=760;update();}});window.lessonState=S;
})();
