const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_PACKAGE||'/Users/baobei/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
const root=path.resolve(__dirname,'..'),url='file://'+path.join(root,'index.html');
const browser=await chromium.launch({executablePath:process.env.CHROME_EXECUTABLE||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const page=await context.newPage(),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});
await page.addInitScript(()=>{window.onerror=(m)=>{let d=document.createElement('div');d.id='ERRBOX';d.textContent=String(m);d.style.cssText='color:white;background:#900;position:fixed;top:0;z-index:9999';document.body?.prepend(d);};});
await page.goto(url);await page.evaluate(()=>document.fonts.ready);assert(await page.locator('.katex').count()===4);assert(await page.locator('.katex-error').count()===0);assert(await page.evaluate(()=>__selftest().ok));
const result={default_pair:await page.locator('#pairTitle').textContent(),tests:[],layouts:[],external_requests:external,browser_errors:errors};assert(result.default_pair==='H4 ↔ H7');
// Every origin and target select, including diagonal and blocked combinations.
for(const a of[1,2,4,5,6,7])for(const b of[1,2,4,5,6,7]){await page.selectOption('#origin',String(a));await page.selectOption('#target',String(b));assert(await page.locator('#pairTitle').textContent()===`H${a} ↔ H${b}`);}result.tests.push('all 36 selector combinations');
await page.locator('#reset').click();for(const n of[1,2,4,5,6,7]){await page.locator(`#molecule [data-pair="${n},7"]`).click();assert(await page.evaluate(()=>lessonState.a)===n);}result.tests.push('all 6 structure sites');
for(const a of[1,2,4,5,6,7])for(const b of[1,2,4,5,6,7]){await page.locator(`#relationMatrix [data-pair="${a},${b}"]`).click();assert(await page.evaluate(()=>[lessonState.a,lessonState.b].join(','))===`${a},${b}`);}result.tests.push('all 36 topology matrix cells');
await page.locator('#reset').click();for(const id of['cosyPlot','tocsyPlot']){const keys=await page.locator(`#${id} [data-pair]`).evaluateAll(els=>els.map(e=>e.dataset.pair));for(const key of keys){await page.locator(`#${id} [data-pair="${key}"]`).click();assert(await page.evaluate(()=>[lessonState.a,lessonState.b].join(','))===key);}}result.tests.push('all default COSY and TOCSY visible markers');
for(const el of await page.locator('.preset button').all()){await el.click();const key=await el.getAttribute('data-pair');assert(await page.evaluate(()=>[lessonState.a,lessonState.b].join(','))===key);}result.tests.push('all 4 presets');
async function range(id,v){await page.locator(id).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},v);}
await page.locator('#reset').click();const cosy=await page.locator('#cosyPlot').innerHTML();for(const t of[0,5,30,60,90,120]){await range('#time',t);assert(await page.locator('#timeValue').textContent()===`${t} ms`);assert(await page.locator('#cosyPlot').innerHTML()===cosy);}await range('#time',0);assert((await page.locator('#tocsyCount').textContent()).includes('0 对'));await range('#time',90);await range('#threshold',.8);assert((await page.locator('#tocsyCount').textContent()).includes('6 对'));assert((await page.locator('#explanation').textContent()).includes('低于阈值'));await range('#threshold',0);assert((await page.locator('#tocsyCount').textContent()).includes('7 对'));result.tests.push('time endpoints / intermediate values, threshold, COSY invariance');
await page.locator('#time').focus();await page.keyboard.press('ArrowRight');assert(await page.evaluate(()=>lessonState.t)===95);await page.locator('#relationMatrix [data-pair="1,2"]').focus();await page.keyboard.press('Enter');assert(await page.evaluate(()=>lessonState.a)===1);await page.locator('#molecule [data-pair="4,2"]').focus();await page.keyboard.press('Space');assert(await page.evaluate(()=>lessonState.a)===4);assert(await page.locator('#molecule [data-pair="4,2"]').evaluate(e=>e===document.activeElement));result.tests.push('keyboard ranges, native buttons and SVG activation, retained focus');
await page.locator('#originalDetails summary').click();assert(await page.locator('#originalDetails').evaluate(e=>e.open));assert(await page.locator('img.original').evaluate(e=>e.complete&&e.naturalWidth===1448));await page.locator('#originalDetails summary').click();for(const b of await page.locator('[data-answer]').all()){await b.click();assert(!(await page.locator('#quizFeedback').textContent()).includes('选择答案'));}await page.locator('#runSelftest').click();assert((await page.locator('#testStatus').textContent()).includes('通过'));result.tests.push('source image details, quiz answers, live selftest');
for(const width of[1440,1280,390,320]){await page.setViewportSize({width,height:1000});await page.locator('#reset').click();await page.evaluate(()=>scrollTo(0,0));await page.evaluate(()=>document.fonts.ready);const layout=await page.evaluate(()=>({viewport:innerWidth,body:document.documentElement.scrollWidth,plots:[...document.querySelectorAll('#cosyPlot svg,#tocsyPlot svg')].map(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})),clippedSVGTexts:[...document.querySelectorAll('#lab svg text')].filter(e=>{const b=e.getBBox(),v=e.ownerSVGElement.viewBox.baseVal;return b.x<-.5||b.x+b.width>v.width+.5||b.y<-.5||b.y+b.height>v.height+.5;}).map(e=>e.textContent),overlappingSVGTexts:[...document.querySelectorAll('#lab svg')].flatMap(svg=>{const ts=[...svg.querySelectorAll('text')];const hits=[];for(let i=0;i<ts.length;i++)for(let j=i+1;j<ts.length;j++){const a=ts[i].getBoundingClientRect(),b=ts[j].getBoundingClientRect();if(Math.min(a.right,b.right)-Math.max(a.left,b.left)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>1)hits.push(ts[i].textContent+' / '+ts[j].textContent);}return hits;}),visiblePanels:[...document.querySelectorAll('#lab>.panel')].every(e=>e.getBoundingClientRect().width>0)}));assert(layout.body<=width);assert(layout.clippedSVGTexts.length===0);assert(layout.overlappingSVGTexts.length===0,JSON.stringify(layout.overlappingSVGTexts));assert(layout.visiblePanels);result.layouts.push(layout);await page.screenshot({path:path.join(root,width===1440?'preview.png':`../mobile-${width}.png`),fullPage:true});if(width===320){await page.locator('#originalDetails summary').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#originalDetails summary').click();await page.locator('.preset [data-pair="4,6"]').click();assert((await page.locator('#pairTitle').textContent()).includes('4 ↔ H6'));}}
assert(errors.length===0);assert(external.length===0);result.passed=true;result.checked_at=new Date().toISOString();result.browser=await browser.version();result.math_formulas=4;result.offline=true;fs.writeFileSync(path.join(root,'verification.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
