(() => {
 'use strict';
 const $=id=>document.getElementById(id), ids=Model.ids;
 const names=['CH₂OH','中间 CH₂','CH₃','OH'], colors=['#ff989c','#f1d775','#5fd0a8','#b9aff4'];
 const defaults={mode:'tocsy',oh:'omit',tau:1.5,threshold:.025,ab:true,bc:true,shifts:[3.6,1.6,.9,2.5],from:0,to:2};
 let state=structuredClone(defaults), graph,weights;
 const el=(name,attrs={},text='')=>{const n=document.createElementNS('http://www.w3.org/2000/svg',name);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text)n.textContent=text;return n;};
 function add(svg,name,attrs={},text=''){const n=el(name,attrs,text);svg.appendChild(n);return n;}
 function clear(svg){svg.replaceChildren();}
 function choose(from,to=from){state.from=from;state.to=to;render();}
 function buttonSVG(svg,attrs,label,action){const n=add(svg,'g',{...attrs,role:'button',tabindex:0,'aria-label':label});n.addEventListener('click',action);n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();action();}});return n;}
 function visible(i,j){return Model.allowed(graph,state.mode,i,j)&&(i===j||weights[i][j]>0&&weights[i][j]>=state.threshold);}
 function labels(){ids.forEach((id,i)=>{if(i<3){$('shift'+id+'Out').textContent=state.shifts[i].toFixed(2);}});$('tauOut').textContent=state.tau.toFixed(2);$('thresholdOut').textContent=state.threshold.toFixed(3);$('tau').disabled=state.mode==='cosy';$('threshold').disabled=state.mode==='cosy';}
 function groups(){const root=$('groupbuttons');root.replaceChildren();ids.forEach((id,i)=>{const b=document.createElement('button');b.className='groupbtn';b.type='button';b.setAttribute('aria-pressed',i===state.from);b.setAttribute('aria-label',`选择 ${id} ${names[i]}`);b.innerHTML=`<strong class="tag${id}">${id} · ${names[i]}</strong><span>${[2,2,3,1][i]}H</span>`;b.disabled=i>=graph.n;b.addEventListener('click',()=>choose(i));root.appendChild(b);});}
 function structure(){const svg=$('structure');clear(svg);const pts=[[205,62],[365,110],[535,62],[65,110]],p=Model.path(graph,state.from,state.to)||[];
   for(const [i,j] of [[3,0],[0,1],[1,2]]){const a=pts[i],b=pts[j];add(svg,'line',{x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:'#9caabb','stroke-width':4});if(p.includes(i)&&p.includes(j)&&Math.abs(p.indexOf(i)-p.indexOf(j))===1)add(svg,'line',{x1:a[0],y1:a[1],x2:b[0],y2:b[1],stroke:'#5fd0a8','stroke-width':7});}
   pts.forEach(([x,y],i)=>{const active=i<graph.n;const g=active?buttonSVG(svg,{},`选择 ${ids[i]} ${names[i]} 的氢组`,()=>choose(i)):add(svg,'g');g.appendChild(el('rect',{x:x-43,y:y-24,width:86,height:48,rx:4,fill:'#151a21',stroke:i===state.from||i===state.to?colors[i]:'#536171','stroke-width':i===state.from||i===state.to?3:1}));g.appendChild(el('text',{x,y:y+6,'text-anchor':'middle',fill:colors[i],'font-size':21,'font-weight':700},i===3?'HO':'C'+(i===2?'H₃':'H₂')));g.appendChild(el('text',{x,y:y+46,'text-anchor':'middle',fill:colors[i],'font-size':17},ids[i]));});
   if(!state.ab||!state.bc)add(svg,'text',{x:300,y:164,'text-anchor':'middle',fill:'#f1d775','font-size':13},'化学键保留；仅在演示网络中移除耦合通路');
 }
 function spectrum(){const svg=$('spectrum');clear(svg);const compact=window.matchMedia('(max-width:540px)').matches,start=compact?106:76,end=580,span=end-start,max=4.6,coord=d=>start+(max-d)/max*span;
   add(svg,'rect',{x:start,y:start,width:span,height:span,fill:'#0e1116',stroke:'#748294'});
   for(const t of [0,1,2,3,4]){const v=coord(t);add(svg,'line',{x1:v,y1:start,x2:v,y2:end,stroke:'#28323e'});add(svg,'line',{x1:start,y1:v,x2:end,y2:v,stroke:'#28323e'});add(svg,'text',{x:v,y:end+24,'text-anchor':'middle',fill:'#b5c1ce','font-size':15},t.toFixed(1));add(svg,'text',{x:start-14,y:v+5,'text-anchor':'end',fill:'#b5c1ce','font-size':15},t.toFixed(1));}
   add(svg,'line',{x1:start,y1:start,x2:end,y2:end,stroke:'#748294','stroke-dasharray':'5 7'});
   const sx=coord(state.shifts[state.from]),sy=coord(state.shifts[state.to]);add(svg,'line',{x1:sx,y1:start,x2:sx,y2:end,stroke:colors[state.from],'stroke-dasharray':'4 5',opacity:.7});add(svg,'line',{x1:start,y1:sy,x2:end,y2:sy,stroke:colors[state.to],'stroke-dasharray':'4 5',opacity:.7});
   for(let i=0;i<graph.n;i++){const v=coord(state.shifts[i]);add(svg,'text',{x:v,y:start-17,'text-anchor':'middle',fill:colors[i],'font-size':17,'font-weight':700},ids[i]);add(svg,'text',{x:end+20,y:v+5,fill:colors[i],'font-size':17,'font-weight':700},ids[i]);}
   let shown=0;
   for(let j=0;j<graph.n;j++)for(let i=0;i<graph.n;i++){if(!visible(i,j))continue;shown++;const x=coord(state.shifts[i]),y=coord(state.shifts[j]),r=7+11*Math.sqrt(weights[i][j]),selected=i===state.from&&j===state.to;
     const g=buttonSVG(svg,{'data-peak':`${ids[i]}-${ids[j]}`},`${ids[i]} 至 ${ids[j]}，${i===j?'对角峰':'交叉峰'}，示意坐标 ${state.shifts[i].toFixed(2)} 与 ${state.shifts[j].toFixed(2)} ppm`,()=>choose(i,j));
     g.appendChild(el('circle',{cx:x,cy:y,r:23,fill:'transparent',stroke:'none'}));
     if(i===j)g.appendChild(el('polygon',{points:`${x},${y-r} ${x+r},${y} ${x},${y+r} ${x-r},${y}`,fill:colors[i],'fill-opacity':.25,stroke:colors[i],'stroke-width':2}));
     else g.appendChild(el('circle',{cx:x,cy:y,r,fill:'#5fd0a8','fill-opacity':.2+weights[i][j]*.5,stroke:'#5fd0a8','stroke-width':2}));
     if(selected)g.appendChild(el('circle',{cx:x,cy:y,r:r+6,fill:'none',stroke:'#eef3f7','stroke-width':3}));
   }
   if(!visible(state.from,state.to))add(svg,'circle',{cx:sx,cy:sy,r:16,fill:'none',stroke:'#eef3f7','stroke-dasharray':'3 5'});
   add(svg,'text',{x:330,y:638,'text-anchor':'middle',fill:'#eef3f7','font-size':17},'F₂ · ¹H 化学位移 / ppm');add(svg,'text',{x:compact?35:22,y:330,transform:compact?'rotate(-90 35 330)':'rotate(-90 22 330)','text-anchor':'middle',fill:'#eef3f7','font-size':17},'F₁ · ¹H 化学位移 / ppm');
   $('plotTitle').textContent=(state.mode==='tocsy'?'TOCSY':'COSY')+' 相关峰中心 · 示意';$('plotState').textContent=`当前显示 ${shown} 个中心`;
 }
 function matrix(){const root=$('matrix');root.replaceChildren();root.style.gridTemplateColumns=`32px repeat(${graph.n},minmax(0,1fr))`;const cell=(text,cl)=>{const n=document.createElement('div');n.textContent=text;n.className=cl;root.appendChild(n);};cell('F₁↓','matrixhead');for(let i=0;i<graph.n;i++)cell(ids[i],'matrixhead');for(let j=0;j<graph.n;j++){cell(ids[j],'matrixhead');for(let i=0;i<graph.n;i++){const allowed=Model.allowed(graph,state.mode,i,j),b=document.createElement('button');b.type='button';b.className=(!allowed?'off ':'')+(i===state.from&&j===state.to?'sel':'');b.dataset.pair=ids[i]+'-'+ids[j];b.setAttribute('aria-label',`${ids[i]} 至 ${ids[j]}，${allowed?'允许':'无相关通路'}，权重 ${weights[i][j].toFixed(4)}`);b.setAttribute('aria-pressed',i===state.from&&j===state.to);b.innerHTML=`${i===j?'◇':allowed?'✓':'×'} ${ids[i]}·${ids[j]}<br>${weights[i][j].toFixed(3)}`;b.addEventListener('click',()=>choose(i,j));root.appendChild(b);}}}
 const conditionText={omit:'默认只讨论原图着色的三个碳上氢组；OH 未作确定归属。',fast:'条件假设：OH 可见但快速交换使 OH–A 的标量传递无效。D 独立，因此额外加入 D–D，未加入 OH 与碳上氢的交叉峰。',slow:'条件假设：OH 交换足够慢，且 OH–A 耦合、传递有效。D–A–B–C 连通，充分传递时理想总数为 16；原图未证实这一条件。',d2o:'D₂O 交换示意：R–OH 变为 R–OD，交换氢的 ¹H 信号可减弱或消失。本模型移除 D，保留碳上氢三组；这不是实测加 D₂O 结果。'};
 function readout(){const {from:i,to:j}=state,allowed=Model.allowed(graph,state.mode,i,j),p=Model.path(graph,i,j);$('pairTitle').textContent=ids[i]+' → '+ids[j];$('pairName').textContent=names[i]+' → '+names[j];$('xRead').textContent=`${state.shifts[i].toFixed(2)} ppm（${ids[i]}，示意）`;$('yRead').textContent=`${state.shifts[j].toFixed(2)} ppm（${ids[j]}，示意）`;
   const kind=i===j?'对角峰':!allowed?'本模式无相关':p.length===2?'直接耦合相关':'接力相关';$('typeRead').textContent=kind;$('weightRead').textContent=weights[i][j].toFixed(4)+(state.mode==='cosy'?'（有 / 无）':'（无量纲）');$('visibleRead').textContent=visible(i,j)?'显示':!allowed?'不显示：无允许路径':'未显示：零权重或低于阈值';$('pathRead').textContent=p?'网络路径：'+p.map(k=>ids[k]).join(' → ')+(i===j?'（同一组）':` · ${p.length-1} 步`):'网络路径：断开';
   $('explainRead').textContent=i===j?'两个坐标来自同一共振位置。对角峰用于定位，不能作为两个不同氢组间的连接证据。':!p?'模型通路已断开，因此这两组不能通过现有链传递。取消勾选只改变教学网络。':!allowed?'耦合链仍有接力路径，但 COSY 对照只保留直接近邻相关。切换 TOCSY 即可比较接力关系。':p.length>2?'两个端点通过中间组接力，相关支持同一自旋系统；不能单凭此峰判断两端直接相邻。': '两组之间有直接耦合边，既是 COSY 对照的连接，也为 TOCSY 接力提供第一步。';
   const c=Model.count(graph,state.mode);$('diagonalCount').textContent=c.diagonal;$('crossCount').textContent=c.cross;$('pairCount').textContent=c.pairs;$('countNote').textContent=`合计 ${c.total} 个理想峰中心。当前阈值与 τ 可能使部分中心未显示；这里统计拓扑允许的位置。`;$('conditionNote').textContent=conditionText[state.oh];
 }
 function zoom(){const svg=$('zoom');clear(svg);const i=state.from,j=state.to,ok=visible(i,j);add(svg,'rect',{x:18,y:18,width:220,height:165,fill:'#0e1116',stroke:'#536171'});add(svg,'line',{x1:128,y1:30,x2:128,y2:172,stroke:'#303a47'});add(svg,'line',{x1:30,y1:100,x2:226,y2:100,stroke:'#303a47'});if(ok){if(i===j)add(svg,'polygon',{points:'128,63 165,100 128,137 91,100',fill:colors[i],'fill-opacity':.25,stroke:colors[i],'stroke-width':3});else for(const r of [18,30,41])add(svg,'ellipse',{cx:128,cy:100,rx:r,ry:r*.72,fill:'none',stroke:'#5fd0a8','stroke-width':2});}else add(svg,'text',{x:128,y:104,'text-anchor':'middle',fill:'#b5c1ce','font-size':15},'未显示峰');add(svg,'text',{x:128,y:210,'text-anchor':'middle',fill:'#b5c1ce','font-size':14},'形状放大 · 示意');add(svg,'text',{x:260,y:52,fill:'#5fd0a8','font-size':24},ids[i]+' → '+ids[j]);add(svg,'text',{x:260,y:92,fill:'#eef3f7','font-size':17},`(${state.shifts[i].toFixed(2)}, ${state.shifts[j].toFixed(2)}) ppm`);add(svg,'text',{x:260,y:135,fill:'#b5c1ce','font-size':15},i===j?'位于对角线上':'镜像 '+ids[j]+' → '+ids[i]);if(i!==j)add(svg,'text',{x:260,y:170,fill:'#eef3f7','font-size':17},`(${state.shifts[j].toFixed(2)}, ${state.shifts[i].toFixed(2)}) ppm`);$('zoomNote').textContent='选择任意峰或矩阵格，放大图、坐标、路径与解释同步更新。';}
 function strip(){const svg=$('strip');clear(svg);for(const v of [0,.5,1]){const y=165-v*120;add(svg,'line',{x1:55,y1:y,x2:575,y2:y,stroke:'#303a47'});add(svg,'text',{x:45,y:y+5,'text-anchor':'end',fill:'#b5c1ce','font-size':14},v.toFixed(1));}for(let j=0;j<graph.n;j++){const x=100+j*120,w=weights[state.from][j];add(svg,'rect',{x:x-24,y:165-w*120,width:48,height:w*120,fill:colors[j]});add(svg,'text',{x,y:195,'text-anchor':'middle',fill:colors[j],'font-size':17},ids[j]);add(svg,'text',{x,y:Math.max(27,155-w*120),'text-anchor':'middle',fill:'#eef3f7','font-size':15},w.toFixed(3));}}
 function assignments(){const desc=['直接连 B；位于氧旁的 CH₂。','直接连 A、C；连接两端的接力节点。','直接连 B；可通过 B 与 A 接力。','交换氢；是否接入由交换与有效耦合共同决定。'];$('assignmentRows').innerHTML=ids.map((id,i)=>`<tr><td data-label="标签 / 原图" class="tag${id}">${id} / ${['红','黄','绿','未着色'][i]}</td><td data-label="氢组">${names[i]}</td><td data-label="理论氢数">${[2,2,3,1][i]}</td><td data-label="示意 δ / ppm">${state.shifts[i].toFixed(2)}${i===3?'（占位）':''}</td><td data-label="耦合与证据">${desc[i]}</td></tr>`).join('');}
 function render(){const focus=document.activeElement;const key=focus?.dataset?.peak||focus?.dataset?.pair;const groupFocus=focus?.closest('#groupbuttons')?Array.from($('groupbuttons').children).indexOf(focus):-1;graph=Model.graph(state.oh,state.ab,state.bc);if(state.from>=graph.n)state.from=0;if(state.to>=graph.n)state.to=2;weights=state.mode==='tocsy'?Model.transfer(graph,state.tau):Array.from({length:graph.n},(_,i)=>Array.from({length:graph.n},(_,j)=>+Model.allowed(graph,'cosy',i,j)));labels();groups();structure();spectrum();matrix();readout();zoom();strip();assignments();if(window.matchMedia("(max-width:540px)").matches){for(const [id,scale] of [["spectrum",1.7],["structure",1.45],["zoom",1.45],["strip",1.55]])$(id).querySelectorAll("text").forEach(n=>n.setAttribute("font-size",+n.getAttribute("font-size")*scale));}if(key){const attr=focus.dataset.peak?'data-peak':'data-pair';document.querySelector(`[${attr}="${key}"]`)?.focus({preventScroll:true});}else if(groupFocus>=0)$('groupbuttons').children[groupFocus]?.focus({preventScroll:true});window.__lessonState={...structuredClone(state),count:Model.count(graph,state.mode),weights,visible:Array.from({length:graph.n},(_,i)=>Array.from({length:graph.n},(_,j)=>visible(i,j)))};}
 function sync(){for(const k of ['mode','oh','tau','threshold','ab','bc'])$(k)[k==='ab'||k==='bc'?'checked':'value']=state[k];ids.slice(0,3).forEach((id,i)=>$('shift'+id).value=state.shifts[i]);}
 ['mode','oh','tau','threshold','ab','bc','shiftA','shiftB','shiftC'].forEach(id=>$(id).addEventListener('input',()=>{if(id.startsWith('shift'))state.shifts[ids.indexOf(id.slice(-1))]=+$(id).value;else state[id]=['ab','bc'].includes(id)?$(id).checked:['tau','threshold'].includes(id)?+$(id).value:$(id).value;render();}));
 $('reset').addEventListener('click',()=>{state=structuredClone(defaults);sync();render();$('quizFeedback').textContent='选择答案查看推理。';});$('endpoint').addEventListener('click',()=>choose(0,2));
 document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{$('quizFeedback').textContent=b.dataset.answer==='ac'?'正确：A 与 C 经 B 接力相连；添加 A–C 和 C–A 两个中心。':'这对已有直接近邻耦合。请考虑两个端点 A 与 C，它们通过 B 接力。';}));
 function renderMath(){const mobile=window.matchMedia('(max-width:540px)').matches;document.querySelectorAll('[data-tex]').forEach(n=>katex.render(mobile&&n.dataset.mobiletex?n.dataset.mobiletex:n.dataset.tex,n,{displayMode:true,throwOnError:true}));}
renderMath();
 const test=Model.selftest();$('selftestStatus').textContent=`模型自检 ${test.ok?'通过':'失败'} · ${test.checks} 组边界组合 · 解析式最大差 ${test.analyticError.toExponential(1)} · 行和最大差 ${test.conservation.toExponential(1)}`;
 window.matchMedia('(max-width:540px)').addEventListener('change',()=>{renderMath();render();});
 sync();render();
})();
