const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const Model=require('./model.js');
const root=path.resolve(__dirname,'..');
const tests=[];
const check=(name,ok)=>{assert(ok,name);tests.push({name,ok});};
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_BIN?{executablePath:process.env.CHROME_BIN}:{channel:'chrome'})});
 const report={clientDate:'2026-10-09',browser:browser.version(),artifactSHA256:require('crypto').createHash('sha256').update(fs.readFileSync(root+'/index.html')).digest('hex'),numerical:Model.selftest(),tests,layouts:[],errors:[],externalRequests:[]};
 check('96 numerical boundary combinations',report.numerical.ok);
 const context=await browser.newContext({viewport:{width:1440,height:1100},deviceScaleFactor:1});
 const page=await context.newPage();
 page.on('pageerror',e=>report.errors.push(e.message));
 page.on('console',msg=>{if(msg.type()==='error')report.errors.push(msg.text());});
 await page.route('**/*',route=>{const url=route.request().url();if(/^https?:/.test(url)){report.externalRequests.push(url);return route.abort();}return route.continue();});
 await page.addInitScript(()=>{window.onerror=(message)=>{const p=document.createElement('p');p.id='errorBanner';p.textContent=message;p.style.color='red';document.body?.prepend(p);};});
 await page.goto('file://'+root+'/index.html');await page.evaluate(()=>document.fonts.ready);
 const read=()=>page.evaluate(()=>window.__lessonState);
 const range=async(id,value)=>page.locator('#'+id).evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input',{bubbles:true}));},String(value));
 check('default full three-site TOCSY answer',(await read()).count.total===9&&await page.locator('[data-peak]').count()===9);
 check('three formulas rendered without errors',await page.locator('.katex-display').count()===3&&await page.locator('.katex-error').count()===0);
 await page.locator('[data-peak="A-C"]').click();check('peak selection updates all linked readouts',await page.locator('#pairTitle').textContent()==='A → C'&&(await page.locator('#pathRead').textContent()).includes('A → B → C')&&await page.locator('[data-pair="A-C"]').getAttribute('aria-pressed')==='true');
 await page.locator('#groupbuttons button').nth(1).click();check('group selection updates source and target',(await read()).from===1&&(await read()).to===1);
 await page.locator('#endpoint').click();
 await page.locator('#mode').selectOption('cosy');check('COSY removes relayed A-C and gives seven centers',(await read()).count.total===7&&await page.locator('[data-peak]').count()===7&&(await page.locator('#typeRead').textContent())==='本模式无相关'&&await page.locator('#tau').isDisabled());
 await page.locator('#mode').selectOption('tocsy');
 await range('tau',0);check('zero mixing gives identity and three displayed centers',(await read()).weights[0][2]===0&&await page.locator('[data-peak]').count()===3);
 await range('tau',1.5);const before=(await read()).weights[0][2];
 await range('tau',3);check('process slider changes relayed model weight',(await read()).weights[0][2]>before);
 await range('tau',1.5);await range('threshold',.3);check('display threshold hides cross centers without altering topology',(await read()).count.total===9&&await page.locator('[data-peak]').count()<9);
 await range('threshold',.025);
 await page.locator('#bc').uncheck();check('broken B-C splits systems 2+1',(await read()).count.total===5&&(await read()).weights[0][2]===0);
 await page.locator('#ab').uncheck();check('both broken edges isolate all three',(await read()).count.total===3);
 await page.locator('#reset').click();
 await page.locator('#oh').selectOption('fast');check('fast exchange gives 3+1 systems and ten centers',(await read()).count.total===10&&(await read()).weights[0][3]===0);
 await page.locator('#groupbuttons button').nth(3).click();check('OH selection shows conditional explanation',(await read()).from===3&&(await page.locator('#conditionNote').textContent()).includes('快速交换'));
 await page.locator('#oh').selectOption('slow');check('slow exchange condition joins four groups',(await read()).count.total===16&&(await read()).weights[0][3]>0);
 await page.locator('[data-pair="D-C"]').click();check('OH relay has three steps',(await page.locator('#pathRead').textContent()).includes('D → A → B → C'));
 await page.locator('#oh').selectOption('d2o');check('D2O mode removes OH and keeps carbon groups',(await read()).count.total===9&&(await read()).from===0&&await page.locator('#groupbuttons button').nth(3).isDisabled());
 await page.locator('#reset').click();
 for(const [id,value,i] of [['shiftA',4.1,0],['shiftB',1.9,1],['shiftC',.55,2]]){const old=await page.locator('[data-peak="'+Model.ids[i]+'-'+Model.ids[i]+'"] polygon').getAttribute('points');await range(id,value);check(id+' changes peak coordinates and table while preserving topology',(await read()).shifts[i]===value&&(await read()).count.total===9&&await page.locator('[data-peak="'+Model.ids[i]+'-'+Model.ids[i]+'"] polygon').getAttribute('points')!==old);}
 await page.locator('#reset').click();await page.locator('#tau').focus();const prev=(await read()).tau;await page.keyboard.press('ArrowRight');check('keyboard adjusts range value',(await read()).tau>prev);
 await page.locator('[data-peak="B-C"]').focus();await page.keyboard.press('Enter');check('keyboard selects SVG peak',(await read()).from===1&&(await read()).to===2&&await page.locator('[data-peak="B-C"]').evaluate(e=>e===document.activeElement));
 await page.locator('[data-pair="C-A"]').focus();await page.keyboard.press('Space');check('keyboard selects matrix cell',(await read()).from===2&&(await read()).to===0);
 await page.locator('[data-answer="ab"]').click();check('quiz incorrect explanation',(await page.locator('#quizFeedback').textContent()).includes('直接近邻'));
 await page.locator('[data-answer="ac"]').click();check('quiz correct explanation',(await page.locator('#quizFeedback').textContent()).includes('正确'));
 await page.locator('summary').click();check('embedded full original opens',await page.locator('details').getAttribute('open')!==null&&await page.locator('details img').evaluate(e=>e.complete&&e.naturalWidth===1462));
 await page.locator('summary').click();await page.locator('#reset').click();
 for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:1100});await page.evaluate(async()=>{window.scrollTo(0,0);await document.fonts.ready;await new Promise(requestAnimationFrame);});const layout=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,overflow:document.documentElement.scrollWidth>innerWidth,mathErrors:document.querySelectorAll('.katex-error').length,equationOverflow:[...document.querySelectorAll(".equation")].some(e=>e.scrollWidth>e.clientWidth+1),images:[...document.images].every(e=>e.complete&&e.naturalWidth>0),svgClips:[...document.querySelectorAll('svg')].flatMap(svg=>[...svg.querySelectorAll('text')].filter(t=>{let b=t.getBoundingClientRect(),s=svg.getBoundingClientRect();return b.left<s.left-.5||b.top<s.top-.5||b.right>s.right+.5||b.bottom>s.bottom+.5;}).map(t=>({svg:svg.id,text:t.textContent}))),height:document.documentElement.scrollHeight}));report.layouts.push(layout);console.log(JSON.stringify(layout));check(width+' viewport: no page overflow, clipping or formula error',!layout.overflow&&!layout.equationOverflow&&!layout.mathErrors&&layout.images&&layout.svgClips.length===0);await page.screenshot({path:root+(width===1440?'/preview.png':'/preview-'+width+'.png'),fullPage:true});}
 await page.setViewportSize({width:320,height:1100});await page.locator('#oh').selectOption('slow');await page.locator('[data-pair="D-C"]').click();const mobile4=await page.evaluate(()=>{window.scrollTo(0,0);return document.documentElement.scrollWidth<=innerWidth;});check('four-group mobile matrix has no overflow',mobile4);await page.screenshot({path:root+'/preview-mobile-oh.png',fullPage:true});
 check('no browser errors',report.errors.length===0);check('zero external requests',report.externalRequests.length===0);
 report.ok=tests.every(t=>t.ok);fs.writeFileSync(root+'/verification.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exit(1);});
